# Generated by Django 2.0 on 2017-12-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('a', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Value A')),
                ('b', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Value B')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmw.Site')),
            ],
        ),
    ]
